### ISSUE TITLE
Version of Lavalink supported?

### ISSUE THREAD

**Issue by archturtle** [MrJohnCoder/SandySounds#12]
Does this lib support lavalink 2.0? And is there a test folder to can use?

**Comment by jtsshieh** [comment]
I think they are getting ready to port to Lavalink 2.x by reading their commits.

**Comment by AnotherGenZ** [comment]
While we do not support Lavalink Version 2.0 at this moment, we are indeed working towards supporting it in the very near future.

**Comment by archturtle** [comment]
Ok!

**Comment by AnotherGenZ** [comment]
@TurtleGamingFTW V2 is now supported. If you encounter any bugs please report them here.

**Comment by archturtle** [comment]
to use Lavalink V2 we use the V2 folder right?

**Comment by AnotherGenZ** [comment]
You would use `SandySounds.Versions.V2(...)`

**Comment by archturtle** [comment]
How would you be able to find the player using the guild id. Im trying `bot.player.get` but that doesnt work

**Comment by AnotherGenZ** [comment]
you would need to do `<SandySounds>.players.get(guildID);`

**Comment by archturtle** [comment]
So i would not fetch by using what i defined `new <Sandy Sounds>` as

**Comment by AnotherGenZ** [comment]
That is correct.
