### ISSUE TITLE
this.client.sendWS is not a function

### ISSUE THREAD

**Issue by Nevvulo** [MrJohnCoder/SandySounds#17]
**Client** `discord.js v12 (master)`
**SandySounds** `Most recent commit (using V2)`

I'm a bit stumped on this, whenever trying to connect to a voice channel using `client.player.join(channel.guild.id, channel.id);`, I am consistently getting `TypeError: this.client.sendWS is not a function` (see [here](https://please.zbot.me/tfRZbwul.png)). 

For context, `client.player` is a `new SandySounds` that looks like this;
```js
client.player = new SandySounds(client, nodes, {
    numShards: 1,
    userId: client.user.id,
    regions: regions,
    defaultRegion: 'us'
  });
```

I've tried manually changing the code so that it properly sends the websocket request, but that just ends up with me getting `Voice connection timeout`, so I'm a bit stuck. I can't tell if this is an issue with me because I've done something wrong, or if it's something else, but any help would be appreciated.

**Comment by AnotherGenZ** [comment]
client is not your bot client. For an example please look at `/src/clients/Default`

**Comment by Nevvulo** [comment]
Ah, sorry about that, thanks for the help! 👍
I'm still getting `Voice connection timeout` for some reason, but that's probably just some fault on my end. Once again, thanks for your help :)

**Comment by Bacon1661** [comment]
@zBlakee Have you found anything with that voice connection timeout? It seems like a fault with lavalink.

**Comment by Nevvulo** [comment]
@Bacon1153 Unfortunately, no, I haven't gotten too far with fixing the issue. I'm also still experiencing it, and I'm still looking for a solution. I'm not sure if it's an issue with Lavalink, I'll have to look into it more, but it's nice to know I'm not the only one experiencing this.
