### ISSUE TITLE
Voice connection timeout

### ISSUE THREAD

**Issue by Bacon1661** [MrJohnCoder/SandySounds#18]
Getting the same error on both your v2 and the original eris-lavalink.
In the bot's console:
```
Error: Voice connection timeout
    at Timeout.pendingGuilds.(anonymous function).timeout.setTimeout [as _onTimeout] (C:\Users\chris\Desktop\baconbot\node_modules\lavalink.js\src\PlayerManager.js:354:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
Lavalink console:
```
[16:11:23] [ INFO ] [[/]] Initializing Spring FrameworkServlet 'dispatcherServlet'
[16:11:23] [ INFO ] [DispatcherServlet] FrameworkServlet 'dispatcherServlet': initialization started
[16:11:23] [ INFO ] [DispatcherServlet] FrameworkServlet 'dispatcherServlet': initialization completed in 17 ms
[16:11:23] [ INFO ] [AudioLoaderRestHandler] GET /loadtracks
[16:11:23] [ INFO ] [GarbageCollectionMonitor] GC monitoring enabled, reporting results every 2 minutes.
[16:11:24] [ INFO ] [AudioLoader] Loaded playlist Search results for: lo-fi
[16:11:24] [ INFO ] [SocketServer] {"op":"connect","guildId":"356197359153315840","channelId":"371378812476194838"}
[16:11:24] [ WARN ] [SocketServer] Unexpected operation: connect
[16:11:34] [ INFO ] [SocketServer] {"op":"disconnect","guildId":"356197359153315840"}
[16:11:34] [ WARN ] [SocketServer] Unexpected operation: disconnect
```

**Comment by Nevvulo** [comment]
I'm also experiencing the same issue, however my console isn't printing the same results. I'm not getting `Unexpected operation` in the console, so I'm not sure why it's happening for me. I've also referenced the issue in #17, so it seems to be a lavalink issue. Hopefully someone can find a solution to this, it's been bugging me over the past few days.

**Comment by Nevvulo** [comment]
@Bacon1153 your stack trace seems to show you are using `lavalink.js` instead of `SandySounds` 🤔 

As for my issue, `voiceServerUpdate` is never getting called, causing the timeout to never be cleared/resolved. I'm not sure why this is, apparently Lavalink is supposed to automatically handle that, but it doesn't seem to be the case for me. I'd appreciate some help on this, other people seem to be experiencing the same problem, and I can't tell if it's because of SandySounds or Lavalink, or something we are doing wrong.

Here's some information; [raw event log](https://please.zbot.me/4mm8foae.png), [stack trace on timeout](https://please.zbot.me/3znE3LVT.png), running latest master on SandySounds and `discord.js`. I've tried switching regions, checking code and everything, yet I just cannot find the source of the issue.

**Comment by Bacon1661** [comment]
@zBlakee Lol sorry I was testing multiple clients so I just drop the contents in the same folder without changing the folder name but I can confirm this is an error from SandySounds.

**Comment by Bacon1661** [comment]
You should also share your findings in the original eris-lavalink client.

**Comment by Nevvulo** [comment]
Ah okay, got a bit confused there 😄
I don't use Eris, so it's a bit difficult for me to test my findings over there, especially with `lavalink.js` not being updated for v2.

**Comment by Bacon1661** [comment]
@zBlakee Still, they're all very similar. Both lavalink.js and SandySounds are just ports from Eris lavalink with very few differences.

**Comment by Bacon1661** [comment]
@zBlakee Brian said that your issue with voiceServerUpdate is a result of not having the correct perms. Are you sure you have all the necessary permissions?

**Comment by jtsshieh** [comment]
You get `Unexpected operation: disconnect` when you use the v1 because in lavalink v2, you don't need to connect.

**Comment by Bacon1661** [comment]
@jtsshieh I get that both in v1 and v2.

**Comment by jtsshieh** [comment]
Oh! That might be the issue. In v2, these ops were removed:

- connect
- disconnect
- validationRes
- isConnectedRes
- validationReq
- isConnectedReq
- sendWS

**Comment by AnotherGenZ** [comment]
Are you guys providing SandySounds a valid client? A valid client example is the default exported one. Furthermore, make sure you guys are waiting for both a voiceServerUpdate and a voiceStateUpdate before calling the voiceServerUpdate on SandySounds.

**Comment by jtsshieh** [comment]
You have to create your own client right? @MrJohnCoder

**Comment by AnotherGenZ** [comment]
Yes, although you could just provide functions to the default client.

**Comment by Nevvulo** [comment]
It'd be nice to get some simple, working example code. Not to be an annoyance, but I'm still pretty lost on how I'm supposed to call voiceServerUpdate myself, and other stuff like that. 👍

**Comment by Bacon1661** [comment]
I +1 this

**Comment by AnotherGenZ** [comment]
I haven’t had the time to make docs and examples yet but I have it on my todo list

**Comment by Nevvulo** [comment]
Alright, sounds good 😄 Hopefully we can see them soon, thanks for all the help

**Comment by Nevvulo** [comment]
Alright, awesome news for my case, finally found out how to pass data to the `voiceServerUpdate` function, and I can finally hear audio! For those suffering from the same issue, here is how you pass the data from the `RAW` event to `voiceServerUpdate` (at least what worked for me);
```js
client.on("raw", message => {
  if (message.t === "VOICE_SERVER_UPDATE") client.player.voiceServerUpdate(message.d);
  if (message.t === "VOICE_STATE_UPDATE") {
      const player = client.player.players.get(message.d.guild_id);
      if (player && player.channel.id !== message.d.channel_id) {
          player.switchChannel(message.d.channel_id);
      }
  }
});
```
You'll probably need to replace `client.player` with what you defined `new SandySounds()` as.

However, this still didn't fix my issue for some reason, and I wasn't sure how I'd be able to efficiently store both `VOICE_SERVER_UPDATE` and `VOICE_STATE_UPDATE` information to later combine into one object and send to `voiceServerUpdate`. So, I decided to modify `SandySounds.js` at the `voiceServerUpdate` function and replace the `data.session_id` value on any `sessionID`s with `client.ws.connection.sessionID` (I manually passed in the client myself). Probably not the cleanest solution, and hopefully I can change the way I do it when John creates an example file/documentation, but it works, and it works fairly nicely for me.

Thanks again for all the help.

**Comment by Bacon1661** [comment]
Looks great! I'll try it when I get home.

**Comment by Bacon1661** [comment]
Unfortunately, it didn't work for me. My ultimate solution was using a different client which worked perfectly and didn't give me any problems at all.

**Comment by AnotherGenZ** [comment]
Could you guys try using the Eris client that I recently added? Want to check if it's your handling of the two packets or if it's your clients.
